# Generated by Django 2.2.1 on 2019-05-18 19:53

import app_base.models
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to=app_base.models.course_image_path)),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('aparat_video', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to=app_base.models.get_upload_path)),
                ('price', models.PositiveIntegerField(default=0, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_base.Course')),
                ('prev_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev', to='app_base.CourseSession')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSessionExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('aparat_video', models.TextField(blank=True, null=True)),
                ('course_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_base.CourseSession')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_base.CourseSessionExercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseByStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('done_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_base.CourseSessionExercise')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttachmentFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attach-files/%y-%m-%d_%H:%M')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
