# Generated by Django 2.2.1 on 2019-06-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='value',
            field=models.CharField(max_length=1200, null=True),
        ),
    ]
